# Generated by Django 5.2 on 2025-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blueprint_materialtype_material_blueprintitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productbp',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='shipment',
        ),
        migrations.AddField(
            model_name='material',
            name='is_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='BlueprintFabric',
        ),
        migrations.DeleteModel(
            name='FabricType',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Fabric',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductBP',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentItem',
        ),
    ]
