# Generated by Django 5.2 on 2025-05-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_fabric_fabric_type_remove_stock_fabric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.blueprint'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
