# Generated by Django 5.2 on 2025-05-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_materialtype_description_materialsubtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=255)),
                ('shipment_date', models.DateTimeField(auto_now_add=True)),
                ('shipment_status', models.CharField(choices=[('pending', 'PENDING'), ('transit', 'TRANSIT'), ('custom', 'CUSTOM'), ('receiving', 'RECEIVING'), ('complete', 'COMPLETE'), ('exception', 'EXCEPTION'), ('failure', 'FAILURE')], default='pending', max_length=255)),
                ('shipment_items', models.ManyToManyField(related_name='shipments', to='api.material')),
            ],
        ),
    ]
