# Generated by Django 5.2 on 2025-06-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_manufactureresource_maximum_slot_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='manufactureplanitem',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('plan', 'PLAN'), ('production', 'PRODUCTION'), ('completed', 'COMPLETED'), ('failure', 'FAILURE')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='manufactureplanitem',
            name='stock_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('operation', models.CharField(choices=[('sale', 'SALE'), ('return', 'RETURN')], default='sale', max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_transactions', to='api.material')),
                ('sale_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_transactions', to='api.saleplace')),
            ],
            options={
                'unique_together': {('date', 'sale_place', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
            ],
            options={
                'unique_together': {('date', 'material')},
            },
        ),
    ]
