# Generated by Django 5.2 on 2025-06-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_manufactureplanitem_manufacture_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufactureplan',
            name='user',
        ),
    ]
