# Generated by Django 5.2 on 2025-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_manufactureplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
