# Generated by Django 5.2 on 2025-06-11 11:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_manufactureplanitem_extra_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceplan',
            old_name='slots',
            new_name='total_slots',
        ),
        migrations.AddField(
            model_name='resourceplan',
            name='used_slots',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='ResoucePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('average_time', models.DurationField(default=datetime.timedelta(0))),
                ('used_slots', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('plan_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manufactureplanitem')),
                ('resource_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_plan_items', to='api.resourceplan')),
            ],
            options={
                'verbose_name': 'Распределение ресурсов',
                'verbose_name_plural': 'Распределение ресурсов',
                'ordering': ['-average_time'],
                'unique_together': {('resource_plan', 'plan_item')},
            },
        ),
    ]
