# Generated by Django 5.2 on 2025-06-11 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_manufactureplanitem_average_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='average_execution_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
