# Generated by Django 5.2 on 2025-06-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_resource_remove_blueprint_resource_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blueprint',
        ),
        migrations.DeleteModel(
            name='ManufacturePlan',
        ),
        migrations.DeleteModel(
            name='ManufacturePlanItem',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourcePlan',
        ),
        migrations.DeleteModel(
            name='SaleTransaction',
        ),
        migrations.DeleteModel(
            name='ShipmentItem',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
