# Generated by Django 5.2 on 2025-06-26 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0006_alter_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintOwner',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.product')),
            ],
            options={
                'verbose_name': 'Blueprint Owner',
                'verbose_name_plural': 'Blueprint Owners',
            },
            bases=('sales.product',),
        ),
    ]
