# Generated by Django 5.2 on 2025-06-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0001_initial'),
        ('sales', '0006_alter_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_values', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('supplement_method', models.CharField(choices=[('raw', 'RAW'), ('buy', 'BUY'), ('manufactured', 'MANUFACTURED'), ('imported', 'IMPORTED')], default='raw', max_length=255)),
                ('item_type', models.CharField(choices=[('product', 'PRODUCT'), ('material', 'MATERIAL'), ('semi-product', 'SEMI-PRODUCT')], default='material', max_length=255)),
                ('shipment_period', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_values', models.TextField(null=True)),
                ('product_link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='material', to='sales.product')),
                ('measure_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material', to='blueprints.unit')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_values', models.TextField(null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_items', to='blueprints.blueprint')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_items', to='blueprints.material')),
            ],
        ),
        migrations.AddField(
            model_name='blueprint',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint', to='blueprints.material'),
        ),
        migrations.DeleteModel(
            name='BlueprintOwner',
        ),
    ]
