# Generated by Django 5.2 on 2025-06-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0002_blueprint_unit_material_blueprintitem_and_more'),
        ('sales', '0007_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='product_link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material', to='sales.product'),
        ),
    ]
