# Generated by Django 5.2 on 2025-06-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_alter_material_product_link'),
        ('sales', '0007_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='blueprints.unit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='product_link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='sales.product'),
        ),
    ]
