# Generated by Django 5.2 on 2025-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0004_alter_material_measure_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='item_type',
            field=models.CharField(choices=[('product', 'PRODUCT'), ('material', 'MATERIAL'), ('semi-product', 'SEMI-PRODUCT')], default='material', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='shipment_period',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplement_method',
            field=models.CharField(choices=[('raw', 'RAW'), ('buy', 'BUY'), ('manufactured', 'MANUFACTURED'), ('imported', 'IMPORTED')], default='raw', max_length=255, null=True),
        ),
    ]
