# Generated by Django 5.2 on 2025-06-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0005_alter_material_item_type_and_more'),
        ('sales', '0007_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='product_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='sales.product'),
        ),
    ]
