# Generated by Django 5.2 on 2025-07-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0006_alter_material_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint', to='blueprints.material'),
        ),
    ]
