# Generated by Django 5.2 on 2025-07-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0007_alter_blueprint_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprint', to='blueprints.material'),
        ),
    ]
