# Generated by Django 5.2 on 2025-07-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0008_alter_blueprint_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintitem',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='blueprints.blueprint'),
        ),
        migrations.AlterField(
            model_name='blueprintitem',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_items', to='blueprints.material'),
        ),
    ]
