# Generated by Django 5.2 on 2025-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0009_alter_blueprintitem_blueprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintitem',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
