# Generated by Django 5.2 on 2025-07-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0010_alter_blueprintitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintitem',
            name='ItemBlueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blueprints.blueprint'),
        ),
        migrations.AlterUniqueTogether(
            name='blueprintitem',
            unique_together={('blueprint', 'material', 'ItemBlueprint')},
        ),
    ]
