# Generated by Django 5.2 on 2025-07-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0011_blueprintitem_itemblueprint_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blueprintitem',
            unique_together=set(),
        ),
    ]
