# Generated by Django 5.2 on 2025-07-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0012_alter_blueprintitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
