# Generated by Django 5.2.4 on 2025-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0013_blueprint_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(null=True, upload_to='materials'),
        ),
    ]
