# Generated by Django 5.2.4 on 2025-08-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0014_material_image'),
        ('sales', '0007_alter_sale_product'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtag',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blueprints.material'),
        ),
        migrations.AlterField(
            model_name='materialtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sales.product'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tags.tag'),
        ),
    ]
