# Generated by Django 5.2 on 2025-06-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product_url'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockTransactions',
            new_name='StockTransaction',
        ),
    ]
