# Generated by Django 5.2 on 2025-06-19 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_stocktransactions_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
