# Generated by Django 5.2 on 2025-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_stocktransaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_date',
            field=models.DateField(),
        ),
    ]
