# Generated by Django 5.2 on 2025-06-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_product_barcode'),
        ('warehouse', '0004_alter_stocktransaction_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.region'),
        ),
    ]
