# Generated by Django 5.2 on 2025-06-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_product'),
        ('warehouse', '0005_alter_warehouse_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sales.product'),
        ),
    ]
