# Generated by Django 5.2 on 2025-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_product_created_at_product_last_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
