# Generated by Django 5.2 on 2025-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fabric_updated_alter_productblueprint_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBlueprint',
            new_name='ProductBP',
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(upload_to='uploads/fabric_img/% Y/% m/% d/'),
        ),
    ]
