# Generated by Django 5.2 on 2025-05-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_productblueprint_productbp_alter_fabric_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(upload_to='fabric_img/'),
        ),
    ]
