# Generated by Django 5.2 on 2025-05-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_material_blueprint_alter_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MaterialSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='api.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='material_sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='api.materialsubtype'),
        ),
    ]
