# Generated by Django 5.2 on 2025-05-28 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactureResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_slot_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Manufacture Resource',
                'verbose_name_plural': 'Manufacture Resources',
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_items',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='average_execution_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='max_day_production',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='minimal_day_production',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='supplement_method',
            field=models.CharField(choices=[('production', 'PRODUCTION'), ('buy', 'BUY')], default='buy', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='materialsubtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='blueprintitem',
            unique_together={('blueprint', 'material')},
        ),
        migrations.CreateModel(
            name='ManufacturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blueprint',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='api.manufactureresource'),
        ),
        migrations.CreateModel(
            name='ManufacturePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('extra_slot', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('alarm', 'ALARM'), ('hight', 'HIGHT'), ('medium', 'MEDIUM'), ('low', 'LOW'), ('sometime', 'SOMETIME LATER')], default='low', max_length=50)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacture_plan_items', to='api.blueprint')),
                ('manufacture_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.manufactureplan')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacture_plan_items', to='api.material')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacture_plan_items', to='api.manufactureresource')),
            ],
            options={
                'unique_together': {('manufacture_plan', 'material', 'blueprint')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='api.material')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'material')},
            },
        ),
    ]
