# Generated by Django 5.2 on 2025-05-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_manufactureresource_remove_shipment_shipment_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='product_name',
            field=models.CharField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufactureplanitem',
            name='priority',
            field=models.CharField(choices=[('low', 'LOW'), ('alarm', 'ALARM'), ('hight', 'HIGHT'), ('medium', 'MEDIUM'), ('sometime', 'SOMETIME LATER')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='blueprint',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='api.blueprint'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplement_method',
            field=models.CharField(choices=[('buy', 'BUY'), ('production', 'PRODUCTION')], default='buy', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='material_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='api.materialvariant'),
        ),
    ]
