# Generated by Django 5.2 on 2025-05-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_materialvariant_material_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureresource',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='manufactureplanitem',
            unique_together={('manufacture_plan', 'material')},
        ),
        migrations.AlterField(
            model_name='manufactureplanitem',
            name='extra_slot',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manufactureplanitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='api.material'),
        ),
        migrations.AlterField(
            model_name='manufactureplanitem',
            name='priority',
            field=models.CharField(choices=[('low', 'LOW'), ('alarm', 'ALARM'), ('high', 'HIGH'), ('medium', 'MEDIUM'), ('sometime', 'SOMETIME LATER')], default='medium', max_length=50),
        ),
        migrations.RemoveField(
            model_name='manufactureplanitem',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='manufactureplanitem',
            name='resource',
        ),
        migrations.CreateModel(
            name='ResourcePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.PositiveIntegerField(default=1)),
                ('extra_slots', models.PositiveIntegerField(default=0)),
                ('manufacture_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_plan_items', to='api.manufactureplan')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_plan_items', to='api.manufactureresource')),
            ],
            options={
                'unique_together': {('manufacture_plan', 'resource')},
            },
        ),
    ]
