# Generated by Django 5.2 on 2025-06-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_manufactureresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureplan',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
