# Generated by Django 5.2 on 2025-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_material_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureresource',
            name='maximum_slot_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='manufactureresource',
            name='minimum_slot_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
