# Generated by Django 5.2 on 2025-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_blueprint_average_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureplanitem',
            name='average_time',
            field=models.DurationField(null=True),
        ),
    ]
