# Generated by Django 5.2 on 2025-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_manufactureplanitem_average_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureplanitem',
            name='average_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
