# Generated by Django 5.2 on 2025-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_manufactureplanitem_average_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='average_execution_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufactureplanitem',
            name='average_time',
            field=models.DurationField(null=True),
        ),
    ]
